// Eindeutschung der Team-/Länder-Namen (football-data liefert sie englisch).
// deTeam("Germany") -> "Deutschland". Unbekanntes -> Original (kein Crash).

const MAP: Record<string, string> = {
  germany: "Deutschland",
  spain: "Spanien",
  france: "Frankreich",
  england: "England",
  italy: "Italien",
  netherlands: "Niederlande",
  belgium: "Belgien",
  portugal: "Portugal",
  croatia: "Kroatien",
  switzerland: "Schweiz",
  austria: "Österreich",
  poland: "Polen",
  denmark: "Dänemark",
  sweden: "Schweden",
  norway: "Norwegen",
  finland: "Finnland",
  iceland: "Island",
  ireland: "Irland",
  "republic of ireland": "Irland",
  scotland: "Schottland",
  wales: "Wales",
  "northern ireland": "Nordirland",
  greece: "Griechenland",
  romania: "Rumänien",
  hungary: "Ungarn",
  czechia: "Tschechien",
  "czech republic": "Tschechien",
  slovakia: "Slowakei",
  slovenia: "Slowenien",
  serbia: "Serbien",
  ukraine: "Ukraine",
  turkey: "Türkei",
  türkiye: "Türkei",
  russia: "Russland",
  brazil: "Brasilien",
  argentina: "Argentinien",
  uruguay: "Uruguay",
  colombia: "Kolumbien",
  ecuador: "Ecuador",
  peru: "Peru",
  chile: "Chile",
  paraguay: "Paraguay",
  bolivia: "Bolivien",
  venezuela: "Venezuela",
  mexico: "Mexiko",
  "united states": "USA",
  usa: "USA",
  "united states of america": "USA",
  canada: "Kanada",
  "costa rica": "Costa Rica",
  panama: "Panama",
  honduras: "Honduras",
  jamaica: "Jamaika",
  japan: "Japan",
  "south korea": "Südkorea",
  "korea republic": "Südkorea",
  "north korea": "Nordkorea",
  australia: "Australien",
  "saudi arabia": "Saudi-Arabien",
  iran: "Iran",
  "ir iran": "Iran",
  qatar: "Katar",
  iraq: "Irak",
  "united arab emirates": "Vereinigte Arabische Emirate",
  jordan: "Jordanien",
  uzbekistan: "Usbekistan",
  china: "China",
  "china pr": "China",
  "new zealand": "Neuseeland",
  morocco: "Marokko",
  senegal: "Senegal",
  nigeria: "Nigeria",
  ghana: "Ghana",
  cameroon: "Kamerun",
  egypt: "Ägypten",
  algeria: "Algerien",
  tunisia: "Tunesien",
  "ivory coast": "Elfenbeinküste",
  "côte d'ivoire": "Elfenbeinküste",
  "cote d'ivoire": "Elfenbeinküste",
  "south africa": "Südafrika",
  "cape verde": "Kap Verde",
  "cape verde islands": "Kap Verde",
  "dr congo": "DR Kongo",
  "congo dr": "DR Kongo",
  mali: "Mali",
  "burkina faso": "Burkina Faso",
};

export function deTeam(name?: string | null): string {
  if (!name) return "";
  return MAP[name.trim().toLowerCase()] ?? name.trim();
}
